### ISSUE TITLE
amd64 Docker Images should be compiled with Redis support 

### ISSUE THREAD

**Issue by mdfranz** [jasonish/docker-suricata#15]
ARM docker images (both 32/64 bit)  are compiled with Redis but Intel Docker images are not -- see https://github.com/jasonish/docker-suricata/blob/a3c3ad0cb6e47fb01fdd7c748e72c5847a1a235c/6.0/Dockerfile.alpine-arm64v8#L58 

Also, is there a reason centos:8 is used as base image and not alpine like on ARM?

**Comment by jasonish** [comment]
Ah, thanks.  I had the dependency installed, but didn't have the ./configure flag.  I'll add and push up some builds in the next day.

As for Alpine vs Alpine, I don't have hard evidence, I've often heard that musl can be a little slower that glibc, and for Suricata that kind of stuff matters.  I also have more trust in CentOS/RHEL as a base-os than Alpine, but thats just gut feeling.  But for ARM, Alpine was just the easiest way to get an image going.

**Comment by mdfranz** [comment]
Sweet!  Heard various argument pro/con over the years, but don't have strong opinions either. I'm actually running more on ARM and they are working well!  See https://gitlab.com/mdfranz/nsm4home/ for how I'm using your docker images 😺

**Comment by mdfranz** [comment]
This is fixed in  

```
jasonish/suricata                           latest        ca7468f9267b   5 days ago      491MB
```
