### ISSUE TITLE
PUID and PGID not working

### ISSUE THREAD

**Issue by jerkball** [jasonish/docker-suricata#16]
RaspBerry Pi 4  - Raspberry OS here... using suricata latest...

With PUID and PGID as environmental docker doesn't start:

/docker-entrypoint.sh: line 11: groupmod: not found

If using just the PUID environmental I get:

/docker-entrypoint.sh: line 15: usermod: not found

Default PUID 100 is systemd-timesync in Raspbian OS... Would like to use the Pi User with ID 1000

Thank you very much!

**Comment by jasonish** [comment]
Trying pulling again, I've made an update. If it still fails, please tell me which image you are pulling.

**Comment by jerkball** [comment]
Seems to work now... deleted everything... Added PGID and PUID... and files are created with correct owner...

No error in logs anymore....

Thanks a lot!
