### ISSUE TITLE
capng_change_id for main thread failed

### ISSUE THREAD

**Issue by hyperreal64** [jasonish/docker-suricata#25]
I'm using Podman on Fedora CoreOS 35. This is the command I'm using:
```bash
sudo podman run --rm -it --net=host --cap-add=net_admin --cap-add=sys_nice jasonish/suricata:latest -i ens3
```

I get the following error:
```bash
<Error> - [ERRCODE: SC_ERR_FATAL(171)] - capng_change_id for main thread failed
```

Thank you for making a Docker image for Suricata. Please let me know if there is anymore info you need to help troubleshoot this. :-)

**Comment by jasonish** [comment]
Thanks for the report.  Appears to be failing on the same way on Fedora 35 and Fedora 34 (it wasn't always on Fedora 34).

I've tried adding a few of the capabilities, but the privilege dropping done by Suricata continues to fail.  The only work-around I know so far is to run with `--privileged` which is a bit unfortunate. I will be looking into this.

**Comment by jasonish** [comment]
For podman you have to add `--cap-add=net_raw` as well now. I'll update the README.

**Comment by jasonish** [comment]
README updated. Let me know if you any other issues.

**Comment by hyperreal64** [comment]
Thank you! It works now.
