### ISSUE TITLE
Output filename

### ISSUE THREAD

**Issue by zzecool** [jasonish/docker-suricata#35]
deleted

**Comment by jasonish** [comment]
Provide your own `suricata.yaml` and set your filenames. See https://github.com/jasonish/docker-suricata#volumes to generate a default config you can then use.

**Comment by zzecool** [comment]
Forgive me i messed the github repos.

**Comment by almereyda** [comment]
Can this be closed?

**Comment by jasonish** [comment]
Yup. Thanks for the ping.
