### ISSUE TITLE
PF_RING support

### ISSUE THREAD

**Issue by jmartini89** [jasonish/docker-suricata#36]
Hello!
Would be great to have PF_RING support in Suricata's image.

As of `jasonish/suricata:7.0.0`:
```
`Error: suricata: PF_RING not enabled. Make sure to pass --enable-pfring to configure when building.
```

**Comment by jasonish** [comment]
The main issue here is that the host still needs to have PF_RING installed itself for the kernel module. Then I'm not sure how in-sync the library version that Suricata is compiled with needs to be with the kernel module, at which point you might need to be building your own Suricata anyways.

Typically I keep these inline with RPM compile time features, which means everything needs to be available by the distro itself.

**Comment by jmartini89** [comment]
AFAIK user-land and kernel-land PF_RING libraries are (usually) compatible on different versions.

A possible solution would be to build a specifically tagged Suricata image, including PF_RING version on the image tag.

I'm not sure about Red Hat Linux based distributions, but on Debian PF_RING is not an available package.
