### ISSUE TITLE
Container is not starting due missing NETMAP

### ISSUE THREAD

**Issue by xtruthx** [jasonish/docker-suricata#37]
Hi,

i pulled the image `latest` . It seems to be an issue with NETMAP. Docker logs is showing:

`Error: suricata: NETMAP not enabled.`
 I tried some OPTIONS of suricata but it wont helps. Seems that the image is completly missing NETMAP.

**Comment by jasonish** [comment]
Suricata is not built with NETMAP support in these containers.  Netmap support requires host support via a kernel module which the container cannot deal with. And then some non-standard packages that would complicate the built.  This is the same reason PF_RING isn't supported either. These containers focus on what is available in Linux itself.
