### ISSUE TITLE
Makefile / ../build.sh: not found  

### ISSUE THREAD

**Issue by JMarianoIFSTTAR** [jasonish/docker-suricata#38]
Just after git clone, invoking make : 

```
for d in master 6.0 5.0 4.1; do \
	(cd $d && ../build.sh); \
done
/bin/sh: 2: ../build.sh: not found
/bin/sh: 2: ../build.sh: not found
/bin/sh: 2: cd: can't cd to 5.0
/bin/sh: 2: cd: can't cd to 4.1
make: *** [Makefile:9 : build] Erreur 2
```

Of course, DIRS should be corrected. 
Anyway, there is no build.sh

**Comment by jasonish** [comment]
Ah, yeah.. The build scripts are a mess right now as their main goal is to build 3 archs and create a multi-architecture manifest for pushing to a registry.

I assume you just want to build a container you can run on the host you are building it on?

**Comment by jasonish** [comment]
Closing. The Makefile's are gone.
