### ISSUE TITLE
`--disable-march-native` seem to be ignored

### ISSUE THREAD

**Issue by ManofWax** [jasonish/docker-suricata#5]
Hello,
When running the container on a Xeon E5-2620 suricata will exit with `error: 132` that looks like to be a SIGILL.

I've tried building the container myself on a i5-6200U and I got the same error when running it on a Xeon.

Looking at the build logs it seems GCC ignores the `--disable-march-native` and builds suricata specifically for the CPU on the build machine. I've fixed the problem by replacing `--disable-march-native` with `--disable-gccmarch-native`

**Comment by jasonish** [comment]
Thanks, looks like I made a typo. Fixed and pushed.
