### ISSUE TITLE
Can't running..

### ISSUE THREAD

**Issue by smarttang** [jasonish/docker-suricata#6]
```
[root@localhost docker-suricata-elk]# ./launcher start -i eth0
Unable to find image 'jasonish/suricata-elk:latest' locally
Trying to pull repository docker.io/jasonish/suricata-elk ... 
Pulling repository docker.io/jasonish/suricata-elk
/usr/bin/docker-current: Error: image jasonish/suricata-elk:latest not found.
See '/usr/bin/docker-current run --help'.
[root@localhost docker-suricata-elk]# 
```

**Comment by jasonish** [comment]
It looks like you are trying to run this project over here: https://github.com/jasonish/docker-suricata-elk

I've abandoned that project. It has not had updates in 4 some years and should not be used. It remains on GitHub as an archived project for reference only.

**Comment by smarttang** [comment]
Will there be a version integrated with ELK in the future?
--------------------------------------------
以后都不会有和ELK集成的版本了吗？

**Comment by jasonish** [comment]
No. This can be used as part of an ELK setup though.  Elastic produces
Docker images for Filebeat and Elastic Search.
